add-global-variants = true
add-panic-variants = true
no-tests = true
output = "db/one"
pkgname = "model"
wire = true

[psql]
  dbname = "admin"
  host = "localhost"
  port = 5434
  user = "admin"
  pass = "admin"
  sslmode = "disable"
