version: '3'
services:
  db1:
    image: postgres:11-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  db2:
    image: postgres:11-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin